FROM ibmjava:8-jre

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
  && apt install tzdata telnet \
  && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ADD fusion-api/target/*-SNAPSHOT.jar /applications/fusion.jar
ADD fusion-simple/target/*-SNAPSHOT.jar /applications/fusion-simple.jar

ENTRYPOINT ["/bin/sh","-c","java -jar -Dfile.encoding=UTF-8 /applications/fusion.jar --spring.profiles.active=test --server.port=8080"]