server:
  port: 8081
nacos:
  config:
    server-addr: 192.168.99.10:31048
    namespace: dev1
    max-retry: 3
    config-long-poll-timeout: 1000
    config-retry-time: 1000
    auto-refresh: true
    username: nacos
    password: nacos
    context-path: /nacos
    group: DEFAULT_GROUP
    file-extension: yaml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.99.10:31048
        namespace: dev1
logging:
  level:
    root: info
    mybatis.mapper: info