pipeline {
    environment { 
        registry = "https://192.168.99.10"
        registryCredential = "harbor-admin"
        gatewayImage = ""
        applicationImage = ""
    }     
    agent {
        kubernetes {
            // inheritFrom 'jenkins-slave'
            label 'jenkins-slave,slave'
        }
    }

    stages {
        stage('Source') {
            steps {
                git credentialsId: 'gitlab-ssh-private-key', branch: 'master', url: 'ssh://git@gitlab.openmpc.com:20220/liucong/privacy.git'
            }
        }
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn clean install -Dmaven.test.skip=true -Dasciidoctor.skip=true'
                }
            }
        }
        stage('Building app image') { 
            steps {
                container('docker') {
                    script {
                        sh "echo build"
                        gatewayImage = docker.build("192.168.99.10/primihub/gateway:${env.BUILD_NUMBER}", "./gateway")
                        applicationImage = docker.build("192.168.99.10/primihub/application:${env.BUILD_NUMBER}", "./application")
                    }
                }
            }
        }
        stage('Push app image') {
            steps {
                container('docker') {
                    script {
                        echo "push stage"
                        docker.withRegistry( registry, registryCredential ) {
                            gatewayImage.push()
                            applicationImage.push()
                        }
                    }
                }
            }
        }
        
    //     stage('Update app image') {
    //         steps {
    //             container('kubectl') {
    //                 sh 'curl -X PUT -H "content-type: application/json" -H "Cookie: KuboardUsername=admin; KuboardAccessKey=6d2kkmpjh6nh.txm5xy2j32scdwpysth32dad86ty4itm" \
    // -d "{"kind":"deployments","namespace":"primihub","name":"gateway","images":"192.168.99.10/primihub/gateway:$BUILD_NUMBER"}" \
    // "http://192.168.99.10:23508/kuboard-api/cluster/primihub/kind/CICDApi/admin/resource/updateImageTag"'
    //                 sh 'curl -X PUT \
    // -H "Content-Type: application/yaml" \
    // -H "Cookie: KuboardUsername=admin; KuboardAccessKey=6d2kkmpjh6nh.txm5xy2j32scdwpysth32dad86ty4itm" \
    // -d "{"kind":"deployments","namespace":"primihub","name":"gateway"}" \
    // "http://192.168.99.10:23508/kuboard-api/cluster/primihub/kind/CICDApi/admin/resource/restartWorkload"'
    //             }
    //         }
    //     }
        
        stage('Deploy') {
            steps {
                container('kubectl') {
                    withKubeConfig([credentialsId: 'k8s-cluster-admin-kubeconfig']) {
                        // sh 'sed -ri "s@image: .*@image: 192.168.99.10/primihub/gateway:$BUILD_NUMBER @g" ./gateway/deploy-gateway.yaml'
                        // sh 'sed -ri "s@image: .*@image: 192.168.99.10/primihub/application:$BUILD_NUMBER @g" ./application/deploy-application.yaml'
                        // sh 'kubectl apply -f ./gateway/deploy-gateway.yaml'
                        // sh 'kubectl apply -f ./application/deploy-application.yaml'
                        sh 'kubectl set image deployment/application application=192.168.99.10/primihub/application:$BUILD_NUMBER'
                        sh 'kubectl set image deployment/gateway gateway=192.168.99.10/primihub/gateway:$BUILD_NUMBER'
                    }                      
                }
            }
        }
        
    }
    // post {
    //     failure {
    //         updateGitlabCommitStatus name: 'build', state: 'failed'
    //     }
    //     success {
    //         updateGitlabCommitStatus name: 'build', state: 'success'
    //     }
    // }

}