server:
  port: 8099

spring:
  datasource:
    name: sqlite3
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${db.path}/simple.db
    username:
    password:

logging:
  level:
    root: info
grpc:
  server:
    port: 9099
db:
  path: /data/fusion/simple
#  path: /Users/zhongziqian/data/fusion/simple

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml

collaborate: http://127.0.0.1:7899/