name: Build and push Docker images
on:
  pull_request:
    branches:
      - main
      - develop

env:
  REGISTRY: docker.io
  FUSION_IMAGE: primihub/primihub-fusion
  PLATFORM_IMAGE: primihub/primihub-platform
  WEB_IMAGE: primihub/primihub-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
    
    # - name: Login to Docker Hub
    #   uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
    #   with:
    #     registry: ${{ env.REGISTRY }}
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker metadata
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push fusin images
      uses: docker/build-push-action@v2
      with:
        context: ./primihub-fusion
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}

    - name: Build and push platform images
      uses: docker/build-push-action@v2
      with:
        context: ./primihub-service
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}

    - name: Build and push web images
      uses: docker/build-push-action@v2
      with:
        context: ./primihub-webconsole
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}