name: Build and push Docker images
on:
  push:
    tags: [ '*.*.*' ]
  pull_request:
    branches:
      - main
      - develop # for test

env:
  REGISTRY: docker.io
  FUSION_IMAGE: primihub/primihub-fusion
  PLATFORM_IMAGE: primihub/primihub-platform
  WEB_IMAGE: primihub/primihub-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
    
    - name: Login to Docker Hub
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker metadata
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38

    - name: Build and push fusin images
      uses: docker/build-push-action@v2
      with:
        context: ./primihub-fusion
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.REGISTRY }}/${{ env.FUSION_IMAGE }}:latest
          ${{ env.REGISTRY }}/${{ env.FUSION_IMAGE }}:${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push platform images
      uses: docker/build-push-action@v2
      with:
        context: ./primihub-service
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.REGISTRY }}/${{ env.PLATFORM_IMAGE }}:latest
          ${{ env.REGISTRY }}/${{ env.PLATFORM_IMAGE }}:${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push web images
      uses: docker/build-push-action@v2
      with:
        context: ./primihub-webconsole
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.REGISTRY }}/${{ env.WEB_IMAGE }}:latest
          ${{ env.REGISTRY }}/${{ env.WEB_IMAGE }}:${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}